name: community_toolkit
description: Community toolkit for Flutter apps. Includes MVVM primitives, command bindings, and messaging utilities.
version: 0.1.0
homepage: https://github.com/M0n7y5/community_toolkit_flutter
repository: https://github.com/M0n7y5/community_toolkit_flutter
issue_tracker: https://github.com/M0n7y5/community_toolkit_flutter/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
